import type { Metadata } from "next";
import { Geist, Geist_Mono, Josefin_Sans } from "next/font/google";
import "../styles/globals.css";
import "../styles/rotating-card.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import HeaderComponent from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const josefinSans = Josefin_Sans({
  weight: ["200", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Profile",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* ${geistSans.variable} ${geistMono.variable} */}
      <body className={`${josefinSans.className} antialiased bg-gray-900`}>
        <HeaderComponent />
        {children}
        <Footer />
      </body>
    </html>
  );
}
